name = "len-industries"
compatibility_date = "2024-09-02"

[env.production]
name = "len-industries"

# Cloudflare Pages configuration
pages_build_output_dir = "."

# Custom domain (optional - uncomment and update when ready)
# routes = [
#   { pattern = "lenindustries.com", custom_domain = true }
# ]

# Environment variables (if needed)
# [env.production.vars]
# ENVIRONMENT = "production"
